version : '3'

services:
  clientui:
    image: liubarnabas/pyclient-ui:v1
    ports:
      - 7000:7000
    depends_on:
      - client
  client:
    image: liubarnabas/pyclient:v1
    ports:
      - 5000:5000
    depends_on:
      - server
  server:
    image: liubarnabas/pyserver:v1
    ports:
      - 80:80
